Issue-441 - Added functionality to position annotations on specific d…
chartjs/chartjs-plugin-annotation pull request #450
Opened 2021-08-03 15:09 UTC by Aukevanoost

…atasets of a barchart

2021-08-05 22:05 UTC, LeeLenaleee commented on src/types/line.js
> +    const isHorizontal = (chart.config.options.indexAxis !== 'y');
Should be a `===` comparrison instead of `!==` because now its giving the opposite result

2021-08-17 08:03 UTC, kurkle commented
I think there are some issues:
- the [x|y][Min|Max] values already support index values on a category scale, so those can already be used to draw the lines
- scale might not be the length of chart area edge [sample](https://www.chartjs.org/docs/latest/samples/scales/stacked.html)
- the `indexAxis` and `type` options can be configured per dataset
- scale.ticks.length is not reliable, ticks can be autoSkipped etc.
- adjusting the line position on bar charts is a breaking change

2021-08-23 13:51 UTC, Aukevanoost commented
@kurkle First of all, thank you for your feedback. I've fixed some of your remarks: 

[x] the [x|y][Min|Max] values already support index values on a category scale, so those can already be used to draw the lines
[x] scale might not be the length of chart area edge sample
[x] the indexAxis and type options can be configured per dataset
[  ] scale.ticks.length is not reliable, ticks can be autoSkipped etc.
[x] adjusting the line position on bar charts is a breaking change

Unfortunately I was not able to fix 'scale.ticks.length' (yet), I was hoping you could provide a suggestion to use for the calculation of the annotation coordinate location. 

Cheers in advance

2021-08-24 10:07 UTC, Aukevanoost commented
As mentioned on #441 It is more robust to use Index instead of a chart-width calculation, therefore the last issue has been resolved using index to calculate the location of the annotation.

2021-09-23 04:55 UTC, kurkle requested changes
Sorry for the stalls in reviews.

This needs a rebase.

Current implementation would not work in some situations, for example: mixed stacked charts.
I think it would be safest to get the x, width / y, height from the actual bar element (metaset.data[index]), where the values would always be calculated considering everything.

The bar element has those props: https://www.chartjs.org/docs/latest/api/interfaces/BarProps.html

As we are trying to get the final values (after animation), [getProps](https://www.chartjs.org/docs/latest/api/interfaces/BarElement.html#getprops) should be used with the `final` set to true.

Something like:
```js
function getBarMeta(chart, annotationFor) {
  const meta = defined(annotationFor) && chart.getDatasetMeta(annotationFor);
  return meta.type === 'bar' ? meta : null;
}

resolveElementProperties(chart, options) {
...
const meta = getBarMeta(chart, options.annotationFor);
if (meta) {
  const bar = meta.data[options.index];
  if (bar.horizontal) { 
    const {x: centerX, width} = bar.getProps(['x', 'width'], true);
    x = centerX - width / 2;
    x2 = centerX + width / 2;
  } else {
    const {y: centerY, height} = bar.getProps(['y', 'height'], true);
    x = centerY - height / 2;
    x2 = centerY + height / 2;
  }
}
if (scale) {
...
```

Also I think the new code should only be executed if `annotationFor` is set. And I think it would be ok to only accept the index (and not label or any other value) for it.
It can be scriptable anyway:
`annotationFor: (ctx) => ctx.chart.data.dataset.findIndex(ds => ds.label === 'foobar')`

It would not hurt to make it work for box and ellipse annotations too.. so putting that in a helper and replacing the x, y, x2, y2 initialization with that would do the trick:

```js
let {top: y, left: x, bottom: y2, right: x2} = getDefaultCoords(chart, options);
```
and the getDefaultCoords would be something like:
```js
function getDefaultCoords(chart, options) {
  let {top: y, left: x, bottom: y2, right: x2} = chart.chartArea;
  const meta = getBarMeta...
  ...
  return {x, y, x2, y2};
}
```

2021-09-23 04:55 UTC, kurkle commented on docs/guide/options.md
> +The [chart](#chart) option context is provided by Chart.js. It is passed to scriptable options when resolving annotation `id`, `type` and `drawTime` or adjusting scale ranges in `afterDataLimits` hoo
Why did you remove `xScaleID` and `yScaleID`?

2021-11-11 20:39 UTC, kurkle commented
Closing as stale. Will reopen if you get back to this.

2021-11-11 20:39 UTC, closed without merging